name: Deploy Portfolio to AWS

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Install frontend dependencies
      - name: Install frontend dependencies
        run: |
          cd frontend
          npm install

      # Build frontend React app
      - name: Build React App
        run: |
          cd frontend
          npm run build

      # Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # Deploy frontend to S3
      - name: Deploy to S3
        run: |
          aws s3 sync frontend/build/ s3://lambda-artifacts-imageproject-kishore --delete

      # Install backend (Lambda) dependencies
      - name: Install backend dependencies
        run: |
          cd backend
          npm install

      # Zip and deploy Lambda function
      - name: Zip and deploy Lambda
        run: |
          cd backend
          zip -r function.zip .
          aws lambda update-function-code \
            --function-name WriteToContactMessagesDynamoDB \
            --zip-file fileb://function.zip
